name: Check .env Change and Trigger B Repo

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  check-env-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v2

      - name: Check if .env file exists
        id: check_env
        run: |
          if [ -f .env ]; then
            echo "env_exists=true" >> $GITHUB_ENV
          else
            echo "env_exists=false" >> $GITHUB_ENV
          fi

      - name: Initialize .env.md5 if .env exists
        if: env.env_exists == 'true'
        run: |
          if [ ! -f .env.md5 ]; then
            md5sum .env > .env.md5
          fi

      - name: Check if .env file has changed
        if: env.env_exists == 'true'
        run: |
          if md5sum -c .env.md5 --status; then
            echo ".env file has not changed."
            echo "env_changed=false" >> $GITHUB_ENV
          else
            echo ".env file has changed."
            echo "env_changed=true" >> $GITHUB_ENV
            md5sum .env > .env.md5  # 업데이트된 해시값 저장
          fi

      - name: Output result
        run: |
          if [ "$env_changed" == "true" ]; then
            echo "The .env file has changed."
          else
            echo "The .env file has not changed."
          fi
